from typing import Any, Dict


def build_reliability_train_args(
    embed_dim: int,
    reliability_hidden_dim: int = 128,
    reliability_rerank_alpha: float = 0.0,
    reliability_loss_weight: float = 1.0,
    scene_loss_weight: float = 0.2,
    rank_loss_weight: float = 0.0,
    calib_loss_weight: float = 0.0,
    mode_risk_threshold_weight_enabled: bool = False,
    mode_risk_threshold_weight_radius: float = 0.25,
    mode_risk_threshold_weight_peak: float = 2.0,
    mode_risk_threshold_weight_base: float = 1.0,
    mode_risk_rank_top_k: int = 0,
    mode_risk_rank_near_threshold_only: bool = False,
    mode_risk_rank_threshold_radius: float = 0.25,
    risk_fde_threshold: float = 2.0,
    risk_miss_threshold: float = 4.0,
    risk_conflict_min_frames: int = 2,
    risk_conflict_threshold: float = 2.0,
    risk_offroad_threshold: float = 2.0,
    risk_scene_rate_threshold: float = 0.5,
    mode_target_policy: str = "fde_only",
    scene_target_policy: str = "target_best_mode_fail",
    risk_conflict_scope: str = "target_to_neighbors",
    freeze_backbone: bool = False,
    **overrides: Any,
) -> Dict[str, Any]:
    args: Dict[str, Any] = {
        "embed_dim": embed_dim,
        "use_reliability": True,
        "reliability_hidden_dim": reliability_hidden_dim,
        "reliability_rerank_alpha": reliability_rerank_alpha,
        "reliability_loss_weight": reliability_loss_weight,
        "scene_loss_weight": scene_loss_weight,
        "rank_loss_weight": rank_loss_weight,
        "calib_loss_weight": calib_loss_weight,
        "mode_risk_threshold_weight_enabled": mode_risk_threshold_weight_enabled,
        "mode_risk_threshold_weight_radius": mode_risk_threshold_weight_radius,
        "mode_risk_threshold_weight_peak": mode_risk_threshold_weight_peak,
        "mode_risk_threshold_weight_base": mode_risk_threshold_weight_base,
        "mode_risk_rank_top_k": mode_risk_rank_top_k,
        "mode_risk_rank_near_threshold_only": mode_risk_rank_near_threshold_only,
        "mode_risk_rank_threshold_radius": mode_risk_rank_threshold_radius,
        "risk_fde_threshold": risk_fde_threshold,
        "risk_miss_threshold": risk_miss_threshold,
        "risk_conflict_min_frames": risk_conflict_min_frames,
        "risk_conflict_threshold": risk_conflict_threshold,
        "risk_offroad_threshold": risk_offroad_threshold,
        "risk_scene_rate_threshold": risk_scene_rate_threshold,
        "mode_target_policy": mode_target_policy,
        "scene_target_policy": scene_target_policy,
        "risk_conflict_scope": risk_conflict_scope,
        "freeze_backbone": freeze_backbone,
    }
    args.update(overrides)
    return args
